### ISSUE TITLE
Bittrex parsing issue in .exchange call

### ISSUE THREAD

**Issue by wilcollins** [mondeja/pymarketcap#10]
`coinmarketcap.exchange('bittrex')` produces the following error:
```
 File "/usr/local/lib/python3.6/site-packages/pymarketcap/core.py", line 595, in exchange
    volume_24h_usd = self.parse_int(_volume_24h_usd)
ValueError: invalid literal for int() with base 10: '\n                                 ** \n                                \n                                    28003900\n                                \n'
```

I'll submit a PR for this tomorrow -- I have a simple fix locally, but I want to clean it up
`_volume_24h_usd = sub(r'\$|,', '', c.getText()).replace('\n', '').replace('*',).strip()`

**Comment by mondeja** [comment]
Thanks you for report it! It's fixed. I think that a regular expression is more efficient: `_volume_24h_usd = sub(r'\$|,|\*| |\s', '', c.getText())`, but let my know if you don't agree.

**Comment by wilcollins** [comment]
That's what I meant by "clean it up" :)

**Comment by wilcollins** [comment]
I was also thinking about adding an integration test for this so it will be caught in CI in the future
