### ISSUE TITLE
Please add is_updated to the markets function

### ISSUE THREAD

**Issue by reteps** [mondeja/pymarketcap#2]
Can you scrape the text for the last time the market was updated? Usually it says "Recently", but if it's not, can you flip the value of a variable "is_updated" accordingly so?

**Comment by mondeja** [comment]
Sorry, but coinmarketcap only gives this word "Recently". How can I sure that the market is updated by other ways?

**Comment by reteps** [comment]
That's fine.

Add this line of code:
```python3
elif n == 6:
    updated = bool(nav == "Recently")
```
And change market to this:
```python3
market = {'exchange': exchange, 'pair': pair,
'24h_volume_usd': volume_24h,
'price_usd': price,
'percent_volume': percent_volume,
'is_updated':updated}
```
Works like a charm for me.

**Comment by mondeja** [comment]
Oh, I understand you now. It's done!
