### ISSUE TITLE
Installation Error: curl.h

### ISSUE THREAD

**Issue by cryptonaut1357** [mondeja/pymarketcap#20]
Hello,

first thanks for your work, the older version was very helpful!
Unfortunately iam unable to install the new version, i tried for a long time today and it didnt worked. 

The error is:
`pymarketcap\curl.c(539): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "curl/curl.h": No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.12.25827\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2`

I read a lot about issues of Visual Studio and Python 3.6, installed it several times, tried another thousand things, also tried to install the libcurl dependencies, but it was all ineffective.

Can you help me maybe somehow?

regards

**Comment by mondeja** [comment]
You have libcurl `.dll` files in your system and, in that case, where are these? What is `cl.exe`? How you are compiling, with `python setup.py install`? Sorry, I'm working on Unix and with this info I can't do much more.

**Comment by mondeja** [comment]
Ok, now you can install the wrapper wihout `libcurl`, instead `urllib` will be used. Download the code and run `setup.py` with the command: `python setup.py install --no-curl`. Any inconvenient let me know.

**Comment by cryptonaut1357** [comment]
THANK YOU my friend!! Some Dragons will fly into your wallet :)

One thing you might want to know: on mybinder comes this error now 
![mybinder](https://user-images.githubusercontent.com/32884602/36143417-5c69cd1c-10ab-11e8-8912-4c1c646fcfb5.JPG)

**Comment by mondeja** [comment]
It's fixed.
