### ISSUE TITLE
  TypeError: tuple indices must be integers or slices, not str

### ISSUE THREAD

**Issue by Wingie** [mondeja/pymarketcap#21]
$ pip3 install https://github.com/mondeja/pymarketcap/archive/master.zip
Collecting https://github.com/mondeja/pymarketcap/archive/master.zip
  Downloading https://github.com/mondeja/pymarketcap/archive/master.zip
     | 604kB 1.2MB/s
    Complete output from command python setup.py egg_info:
    Precompiling pymarketcap source code...
    Pymarketcap source code precompiled successfully.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/tn/pdqwb3cx1053ltsy9zgmrzt5_pspzj/T/pip-fowkhzpy-build/setup.py", line 70, in <module>
        package_data["pymarketcap"].extend(["curl.pxd", "curl.pyx"])
    TypeError: tuple indices must be integers or slices, not str

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/tn/pdqwb3cx1053ltsy9zgmrzt5_pspzj/T/pip-fowkhzpy-build/

**Comment by mondeja** [comment]
Fixed
