### ISSUE TITLE
Find coin volume from timestamp to timestamp for an exchange.

### ISSUE THREAD

**Issue by reteps** [mondeja/pymarketcap#22]
I'm trying to figure out the x hour volume for a coin on an exchange.

For example:

+ NANO on Binance from 9AM - 10AM
+ BTC on Kucoin from 9AM - 1PM

Is this able to do that? I know it can do all volume, but exchange specific?

**Comment by mondeja** [comment]
Sorry, but you can't get volume of a currrency at time period of hours.

**Comment by reteps** [comment]
I think you can, with graphs.currency, and subtracting the starting and ending volume for a unix start / end.

**Comment by mondeja** [comment]
It's done. You can now pass datetime in the method as `start` end `end` parameters and the timestamps in response are in datatime also.
