### ISSUE TITLE
Issue with scraped historical volumen and marketcap?

### ISSUE THREAD

**Issue by cryptonaut1357** [mondeja/pymarketcap#24]
Hi, 

this code:
```
`start = datetime(2017, 1, 1)
end = datetime(2018,3,8)
symbol1 = "BTC"

chart1 = cmc.historical(symbol1, start, end, revert=True)
chart1`
```

gives me this output:
```
`{'close': 9395.01,
  'date': datetime.datetime(2018, 3, 8, 0, 0),
  'high': 10147.4,
  'low': 9335.87,
  'market_cap': 10147.4,
  'open': 9951.44,
  'volume': 9951.44}]`
```
OHLC are fine just volume and market cap are are not the same as on cmc. 

![cmcbtcvolmcap](https://user-images.githubusercontent.com/32884602/37207805-f1e10062-239e-11e8-92b8-124933f95729.JPG)

Did i overlook somethink?

regards

**Comment by mondeja** [comment]
Thank for your report. [It's fixed](https://github.com/mondeja/pymarketcap/commit/d55442e475076f926d869f248010e980f8bcfa36).
