### ISSUE TITLE
Google Cloud VM install

### ISSUE THREAD

**Issue by Abolah** [mondeja/pymarketcap#30]
Heyo, 
I'm trying to install the package on a google cloud VM (ubuntu 17.10) and I get this error.
![image](https://user-images.githubusercontent.com/10921309/37559951-5581140e-2a2f-11e8-873a-0251d93dec38.png)

Do you know how to solve this issue?

**Comment by mondeja** [comment]
Install `curl` executing `apt-get install libcurl4-gnutls-dev`or with:
```
wget http://curl.haxx.se/download/curl-7.50.2.tar.gz
tar -xvf curl-7.50.2.tar.gz
cd curl-7.50.2
./configure
make
sudo make install
````

Then install pymarketcap: `pip3 install pymarketcap`
_________________________________

If you want to install without `curl` or the previous option doesn't work try installing from source:

```
git clone https://github.com/mondeja/pymarketcap.git
cd pymarketcap
pip3 install -r requirements.txt
python setup.py install --no-curl
```

**Comment by Abolah** [comment]
Worked perfectly. Thank you !
