### ISSUE TITLE
Failing to install pymarketcap

### ISSUE THREAD

**Issue by Bragegs** [mondeja/pymarketcap#36]
**Command:**

`pip3 install pymarketcap --upgrade
`

Python 3.6.3
Mac OSX

**Output:**

> Collecting pymarketcap
>   Using cached pymarketcap-3.9.147.tar.gz
>     Complete output from command python setup.py egg_info:
>     Error installing dependencies, installing pymarketcap anywhere...
>     Precompiling pymarketcap source code...
>     Error precompiling pymarketcap source code.
>     Restoring pymarketcap source code...
>     Pymarketcap source code restored successfully.
>     Precompiling pymarketcap source code...
>     Pymarketcap source code precompiled successfully.
>     Compiling pymarketcap/core.pyx because it changed.
>     Compiling pymarketcap/curl.pyx because it depends on /Users/bragegs/.pyenv/versions/3.6.3/envs/eit/lib/python3.6/site-packages/Cython/Includes/libc/string.pxd.
>     [1/2] Cythonizing pymarketcap/core.pyx
>     [2/2] Cythonizing pymarketcap/curl.pyx
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/private/tmp/pip-build-3ac6pckj/pymarketcap/setup.py", line 165, in <module>
>         with open(LONG_DESC_PATH, "r") as f:
>     FileNotFoundError: [Errno 2] No such file or directory: '/private/tmp/pip-build-3ac6pckj/pymarketcap/doc/meta/long_desc_raw.txt'
>     
> Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-3ac6pckj/pymarketcap/

**Comment by Bragegs** [comment]
I forked the repo and  removed:

```
LONG_DESC_PATH = os.path.join(CURR_DIR, "doc/meta/long_desc_raw.txt")
with open(LONG_DESC_PATH, "r") as f:
    LONG_DESC = f.read()
```
and changed LONG_DESC variable to contain the innovative:

`LONG_DESC = 'long description'` and it solved the problem.

I can make a PR but i do not know if you want me to copy the content of long_desc_raw.txt and paste as text inside setup.py or to fix the pathing-problem to long_desc_raw.txt.

**Comment by mondeja** [comment]
It's fixed, thanks

**Comment by saulocatharino** [comment]
The error is still occurring, it has not been fixed.

I have the same problem.

**Comment by saulocatharino** [comment]
When I Use:
pip3 install pymarketcap

    Complete output from command python setup.py egg_info:
    Error installing dependencies, installing pymarketcap anywhere...
    Precompiling pymarketcap source code...
    Error precompiling pymarketcap source code.
    Restoring pymarketcap source code...
    Error restoring pymarketcap source code.
    Error building pymarketcap.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-bl9uq1d5/pymarketcap/
