### ISSUE TITLE
Cannot work under my Ubuntu 16.04LTS

### ISSUE THREAD

**Issue by almipa** [mondeja/pymarketcap#39]
Steps:
1. python 3.6.4 was installed from source
2. Cython was installed by pip
3. pymarketcap was installed from source

Python 3.6.4 (default, Mar 22 2018, 01:56:58) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pymarketcap import Pymarketcap
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pam/sandbox/pymarketcap/pymarketcap/__init__.py", line 14, in <module>
    from pymarketcap.core import Pymarketcap
ModuleNotFoundError: No module named 'pymarketcap.core'
>>> 
Any ideas?

**Comment by mondeja** [comment]
Try `sudo pip3 install pymarketcap`.

**Comment by almipa** [comment]
The same result...
May be any error into pymarketcap.core module when we try to import it?

**Comment by mondeja** [comment]
Paste here the output of pymarketcap installation.

**Comment by almipa** [comment]
Sorry, it was my problem. All OK now.
Thank you for pymarketcap!
