### ISSUE TITLE
ranks() showing the same coin symbol for each gainer

### ISSUE THREAD

**Issue by cryptonaut1357** [mondeja/pymarketcap#43]
Hello, found a bug:

`x = cmc.ranks()`
`print(x["gainers"]["1h"])`

returns:

``[{'name': 'HTMLCOIN', 'symbol': 'HTML', 'volume_24h': 228680.0, 'price': 0.000312405, 'percent_change': 31.21}, {'name': 'HTMLCOIN', 'symbol': 'HTML', 'volume_24h': 228680.0, 'price': 0.000312405, 'percent_change': 31.21}, {'name': 'HTMLCOIN', 'symbol': 'HTML', 'volume_24h': 228680.0, 'price': 0.000312405, 'percent_change': 31.21}, {'name': 'HTMLCOIN', 'symbol': 'HTML', 'volume_24h': 228680.0, 'price': 0.000312405, 'percent_change': 31.21}, {'name': 'HTMLCOIN', 'symbol': 'HTML', 'volume_24h': 228680.0, 'price': 0.000312405, 'percent_change': 31.21}, {'name': 'HTMLCOIN', 'symbol': 'HTML', 'volume_24h': 228680.0, 'price': 0.000312405, 'percent_change': 31.21}, {'name': 'HTMLCOIN', 'symbol': 'HTML', 'volume_24h': 228680.0, 'price': 0.000312405, 'percent_change': 31.21}, {'name': 'HTMLCOIN', 'symbol': 'HTML', 'volume_24h': 228680.0, 'price': 0.000312405, 'percent_change': 31.21}, {'name': 'HTMLCOIN', 'symbol': 'HTML', 'volume_24h': 228680.0, 'price': 0.000312405, 'percent_change': 31.21}, {'name': 'HTMLCOIN', 'symbol': 'HTML', 'volume_24h': 228680.0, 'price': 0.000312405, 'percent_change': 31.21}, {'name': 'HTMLCOIN', 'symbol': 'HTML', 'volume_24h': 228680.0, 'price': 0.000312405, 'percent_change': 31.21}, {'name': 'HTMLCOIN', 'symbol': 'HTML', 'volume_24h': 228680.0, 'price': 0.000312405, 'percent_change': 31.21}, ....``

regards

**Comment by mondeja** [comment]
It's fixed, thanks for report it!
