### ISSUE TITLE
listings limit argument

### ISSUE THREAD

**Issue by reteps** [mondeja/pymarketcap#48]
i'm switching from ticker to listings, but it is missing this argument. Can you fix this?

**Comment by mondeja** [comment]
Sorry but doesn't exists a `limit` valid argument on `listings` coinmarketcap API endpoint. If you want to retrieve a certain number of currencies you can do:
```
cmc.cryptocurrencies[:limit]
```

This works also:
```
cmc.listings()["data"][:limit]
```

**Comment by reteps** [comment]
so I used to use `ticker(limit=100)`, what is the equivalent of that? I need the name and ID.

**Comment by mondeja** [comment]
Is the same `ticker(limit=100)`
