### ISSUE TITLE
Coin Ticker duplication

### ISSUE THREAD

**Issue by Abolah** [mondeja/pymarketcap#49]
Heyo,
On coinmarketcap the coin Kyber Network (KNC) has the same as the coin KingN Coin (KNC)
How can I handle it using your lib ?
I'm doing this 
`coin = "KNC"
cmc_json = coinmarketcap.ticker(coin, convert="EUR")`
And here is the printed output:
`{'data': {'id': 1743, 'name': 'KingN Coin', 'symbol': 'KNC', 'website_slug': 'kingn-coin', 'rank': 1286, 'circulating_supply': 2009.0, 'total_supply': 2509.0, 'max_supply': 420000.0, 'quotes': {'USD': {'price': 13.9831, 'volume_24h': None, 'market_cap': 28093.0, 'percent_change_1h': None, 'percent_change_24h': -1.09, 'percent_change_7d': -13.45}, 'EUR': {'price': 11.859626434, 'volume_24h': None, 'market_cap': 23826.0, 'percent_change_1h': None, 'percent_change_24h': -1.09, 'percent_change_7d': -13.45}}, 'last_updated': 1526771052}, 'metadata': {'timestamp': 1526830060, 'error': None}}
`
Can you help me ?

**Comment by mondeja** [comment]
```python
coin = "kyber-network"
cmc_json = coinmarketcap.ticker(coin, convert="EUR")
```
