### ISSUE TITLE
space handling broken

### ISSUE THREAD

**Issue by reteps** [mondeja/pymarketcap#5]
`markets = cmc.markets("BCH")`
gives the error:
`pymarketcap.core.CoinmarketcapError: [Errno 404] https://coinmarketcap.com/currencies/Bitcoin Cash/`

because there isn't a space, there is an underscore.

**Comment by mondeja** [comment]
Thanks for your reports. It's fixed. Also, now you can install the latest version with `pip3 install pymarketcap`.
