### ISSUE TITLE
Binder Error 404

### ISSUE THREAD

**Issue by Abolah** [mondeja/pymarketcap#55]
Heyo,
I'm having this error when lauching the binder doc
![image](https://user-images.githubusercontent.com/10921309/40657990-068634ac-634a-11e8-837b-a2c86d1f8982.png)

here is the url : 
https://hub.mybinder.org/user/mondeja-pymarketcap-5bhlw4yb/tree/docs/sync_live.ipynb

Can you solve the issue ?

**Comment by mondeja** [comment]
[It's fixed](https://mybinder.org/v2/gh/mondeja/pymarketcap/master?filepath=doc%2Fsync_live.ipynb). Only change `docs` with `doc` in the url.
