### ISSUE TITLE
issue with historical api

### ISSUE THREAD

**Issue by niallroche** [mondeja/pymarketcap#56]
**Describe the bug**
the historical method of Pymarketcap returns inconsistent historical values for volume and market cap on some currencies/tokens. On certain coins AVT, Binance Coin, Bitcoin Cash, BitRent and others the market cap and volume properties are the wrong way around and also reference values from the previous day.

**To Reproduce**
1. Execute method  'historical' of `Pymarketcap` class e.g. cmc.historical("ATL", start=datetime(2018, 1, 13))
2. the 'history' list returns the 'market_cap' containing the data from volume 
3. the 'volume' contains values from the **previous** days market cap

**Expected behavior**
The api should mirror the same values as on the website see https://coinmarketcap.com/currencies/atlant/historical-data/?start=20180616&end=20180716 for correct values for ATL 

I think this may be due to the regular expressions in parsing the websites, it seems fine for some tokens, maybe the html output is slightly different ?

**Comment by mondeja** [comment]
Thanks for your report. I think that is fixed on [last commit](https://github.com/mondeja/pymarketcap/commit/306a395f29045a19562022d9c3007050d0dcb101#diff-2a1f13479e5603b888fcfad48c55d531). Please reopen this issue if you experiment troubles with other currencies.
