### ISSUE TITLE
every_currency() in AsyncPymarketcap: the input coin list can include duplicated symbol

### ISSUE THREAD

**Issue by jjcc** [mondeja/pymarketcap#57]
**Coin symbol is not unique in coin list, the method use the first one**
There are a few coins share the same symbol. For example, HOT can be "holo" with rank 77 and id 2682， but could also be "Hydro Protocol" of rank of 307 and id 2430. The method return "Hydro Protocol" because the id is before "holo" but the rank of "holo" actually is within 100. There are a few other samples 

**To Reproduce**
1. Execute method  'ticker()' of `Pymarketcap` class to get first 100 coins
2. Get the symbol list of the result
3. Call the 'every_currency()' method of AsyncPymarketcap to retrieve the 100 detail information
4. Sort the result by rank. You will get last 4 with rank higher than 100."Hydro Protocol" is one of them  

**Expected behavior**
The expected return of HOT is "holo" with rank of 77 instead of "Hydro Protocal"

**Suggestion**
Give an option of id list as input in addition to symbol list. id is unique. It can be retrieved by "ticker()" method

**Comment by jjcc** [comment]
Actually I traced into the code and found that the list should be able to handle id as long as list of integer is used. The code can detect if it's symbol or id. However when I feed with list of id's, it still failed. I couldn't trace into Cython so I stopped here.

**Comment by mondeja** [comment]
I think that is fixed on [last commit](https://github.com/mondeja/pymarketcap/commit/1dfed5d24dc9c356423577043602a397184be05e). Now you can use this:

```
async with AsyncPym() as apym:
    async for currency in apym.every_currency(currencies=["BTC", "ETH", "steem", "lisk", 1]):
        print(currency)
```
So retrieve currencies by id, it's the most secure way.  If you still experiments that problem, reopen this issue please. Thank you very much!
