### ISSUE TITLE
The wrapper stopped working

### ISSUE THREAD

**Issue by Abolah** [mondeja/pymarketcap#58]
**Error output**
pymarketcap.errors.CoinmarketcapHTTPError404: Status code -> 404 | Url -> https://api.coinmarketcap.com/v2/ticker/1?convert=EUR

**Comment by Abolah** [comment]
it seems like it's working again. Maybe it was an issue on coinmarketcaps Side ?

**Comment by mondeja** [comment]
It's possible.
