### ISSUE TITLE
Consider CoinGecko API for market data

### ISSUE THREAD

**Issue by tmlee** [mondeja/pymarketcap#59]
**Describe the solution you'd like**
If you are looking for freely available market data, may I suggest considering our API at https://www.coingecko.com/api/docs/v3

No api keys needed and rate limit lenient. Our goal is to allow access to data with lower barrier to entry.

Let me know what you think, happy to answer questions and address concerns you may have.

**Comment by mondeja** [comment]
I dont have time because Im working in other projects. But if someone wants to use pymarketcap's backend I'm available to answer all questions related to.
