### ISSUE TITLE
Differently named things on coinmarketcap?

### ISSUE THREAD

**Issue by reteps** [mondeja/pymarketcap#6]
Not sure if this is possible to fix, but I tried to scrape `Bytecoin`, and it gave an 404 error trying to get `https://coinmarketcap.com/currencies/Bytecoin/` when it was `https://coinmarketcap.com/currencies/bytecoin-bcn/`. Not sure what the fix is, or how big this error is.

**Comment by mondeja** [comment]
It's fixed, thanks!
