### ISSUE TITLE
URL parse errors (Bracket handling, use ID, no attribute 'find_all')

### ISSUE THREAD

**Issue by reteps** [mondeja/pymarketcap#7]
# Suggestion
Please create this unit test:
```python
cmc = pymarketcap.Pymarketcap()
for coin in cmc.ticker():
    markets = cmc.markets(coin["symbol"])
```

# Details
Anyways, `https://coinmarketcap.com/currencies/ICON-[Futures]/` should have brackets removed and parsed as `https://coinmarketcap.com/currencies/ICON-Futures/`.

Error #6 was not fixed and `https://coinmarketcap.com/currencies/Bytecoin/` should be `https://coinmarketcap.com/currencies/Bytecoin-bcn/`.

` https://coinmarketcap.com/currencies/Byteball-Bytes/` is actually `https://coinmarketcap.com/currencies/byteball/`. and the same with `https://coinmarketcap.com/currencies/Santiment-Network-Token/` being `https://coinmarketcap.com/currencies/Santiment/`.

lastly, Gnosis gave me the error: `'NoneType' object has no attribute 'find_all'`

# Conclusion
+ try using the coin id for url grabbing if possible. this fixes the error with bytcoin, byteball and santiment.
+ use regex or replace to remove brackets from url if needed.
+ fix the error `'NoneType' object has no attribute 'find_all'`

**Comment by mondeja** [comment]
```python
>>> cmc.markets("icon-futures")
[{'exchange': 'HitBTC', 'pair': 'ICX-BTC', '24h_volume_usd': 418049, 'price_usd': ... }]
>>> cmc.markets("ICX")
[{'exchange': 'HitBTC', 'pair': 'ICX-BTC', '24h_volume_usd': 418049, 'price_usd': ... }]
```
And also is working with santiment (SAN), byteball (GBYTE), gnosis-gno (GNO) and so on...

Sorry but if you want to call as id (santimen, byteball), you need to pass the currency as appears in the URL. Find the currency in google `coinmarketcap Byteball` and extract the currency id from the URL `https://coinmarketcap.com/es/currencies/byteball/  <----` as indicates in [docs](https://github.com/mondeja/pymarketcap/wiki#currency-markets).
