### ISSUE TITLE
Distinguishing between coins with same symbol

### ISSUE THREAD

**Issue by mudisdirty** [mondeja/pymarketcap#8]
When I attempt to query the markets for the coin BAT.  I get the results for batcoin.  This coin seems to be a dead project.  The coin I would like to see the results of is for basic attention token.  Is there a way to distinguish between coins with the same abbreviations?

**Comment by mondeja** [comment]
You can call all methods by symbol or id:
```
cmc = Pymarketcap()
cmc.markets("batcoin")
cmc.markets("basic-attention-token")
```
Find the currency in google `coinmarketcap Basic Attention Token` and extract the currency id from the URL `https://coinmarketcap.com/es/currencies/basic-attention-token/  <----` as indicates at [docs](https://github.com/mondeja/pymarketcap/wiki#currency-markets).
